blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.klaam.ai
    about: Read the docs first
  - name: Discussions
    url: https://github.com/orgs/klaam-ai/discussions
    about: Ask questions here
